# Tap's
tap "homebrew/bundle"
tap "hudochenkov/sshpass"

# Brew's

brew "azure-cli"
brew "python@3.12"
brew "curl"
brew "dos2unix"
brew "git"
brew "go"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "nmap"
brew "node"
brew "openjdk"
brew "sl"
brew "sonar-scanner"
brew "telnet"
brew "thefuck"
brew "tree"
brew "watch"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "hudochenkov/sshpass/sshpass"

# Cask's

cask "anki"
cask "docker"
cask "gimp"
cask "google-chrome"
cask "iterm2"
cask "macs-fan-control"
cask "notion"
cask "postman"
cask "powershell"
cask "qbittorrent"
cask "rectangle"
cask "tableplus"
cask "visual-studio-code"
cask "git-credential-manager"
cask "logi-options-plus"
cask "handbrake"

# MAC Store Apps

mas "Color Picker", id: 1545870783
mas "Grammarly for Safari", id: 1462114288
mas "HP Smart", id: 1474276998
mas "Notion Web Clipper", id: 1559269364
mas "WhatsApp", id: 1147396723

# VSCode plugins

vscode "42crunch.vscode-openapi"
vscode "dbaeumer.vscode-eslint"
vscode "digitalbrainstem.javascript-ejs-support"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "equinusocio.vsc-material-theme"
vscode "equinusocio.vsc-material-theme-icons"
vscode "esbenp.prettier-vscode"
vscode "file-icons.file-icons"
vscode "formulahendry.auto-close-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "kevinrose.vsc-python-indent"
vscode "maracko.json-to-go"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.live-server"
vscode "ms-vscode.powershell"
vscode "mushan.vscode-paste-image"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "sidthesloth.html5-boilerplate"
vscode "streetsidesoftware.code-spell-checker"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-icons-team.vscode-icons"
vscode "wayou.vscode-todo-highlight"
vscode "wholroyd.jinja"
vscode "xabikos.javascriptsnippets"
